import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'jmull_000' at '12/24/16 11:39 AM' with Gradle 3.2.1
 *
 * @author jmull_000, @date 12/24/16 11:39 AM
 */
public class MapThingTest {
    @Test public void testSomeLibraryMethod() {
        MapThing mapThing = new MapThing();
        assertNotNull(mapThing);
        String[] args = new String[0];
        MapThing.main(args);
    }
}
